---
 - name: Creating a yum repository called 'adhoc'
   hosts: all
   tasks:
   - name: Creating a BaseOS Repository
     ansible.builtin.yum_repository:
      name: "baseos"
      description: "Baseos Description"
      baseurl: "https://cdn.redhat.com/content/dist/rhel9/$releasever/aarch64/baseos/os"
      #gpgcheck: true
      ##gpgkey: "http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release"
      enabled: true
   - name: Creating an AppStream Repository
     ansible.builtin.yum_repository:
      name: "appstream"
      descriptions: "App Description"
      baseurl: "https://cdn.redhat.com/content/dist/layered/rhel9/aarch64/cnv/4.13/source/SRPMS"
      ##gpgcheck: true
      #gpgkey: "http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release"
      enable: true
