---
 - name: Creating a yum repository called 'adhoc'
   hosts: all
   tasks:
   - name: Creating a BaseOS Repository
     ansible.builtin.yum_repository:
      name: "baseos"
      description: "Baseos Description"
      baseurl: "http://content/rhel9.0/x86_64/dvd/BaseOS"
      gpgcheck: true
      gpgkey: "http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release"
      enabled: true
   - name: Creating an AppStream Repository
     ansible.builtin.yum_repository:
      name: "appstream"
      descriptions: "App Description"
      baseurl: "http://content/rhel9.0/x86_64/dvd/AppStream"
      gpgcheck: true
      gpgkey: "http://content.example.com/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release"
      enable: true
