---
- name: File manipulation on target hosts
  hosts: all
  tasks:
   - name: Create a file if it does not exist
     file:
      path: /home/student/
      state: directory
      mode: 0755
      owner: student
      group: student
