---
- name: Package Management
  hosts: all
  become: true
  tasks:
   - name: Installing httpd
     dnf:
      name: httpd
      state: present
   - name: Starting the service
     service:
      name: httpd.service
      enabled: true
      state: started
